# Numpy

## Лабораторная работа №1.1

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [1]:
import numpy as np


recipes = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
recipes[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [2]:
minutes_average_value = np.average(recipes[:,1])
minutes_min = np.min(recipes[:,1])
minutes_max = np.max(recipes[:,1])
minutes_median = np.median(recipes[:,1])
print('Среднее значение для минут = ', minutes_average_value)
print('Минимальное значение для минут = ', minutes_min)
print('Максимальное значение для минут = ', minutes_max)
print('Медиана для минут = ', minutes_median)

Среднее значение для минут =  21601.00169
Минимальное значение для минут =  0
Максимальное значение для минут =  2147483647
Медиана для минут =  40.0


In [3]:
ingredients_average_value = np.average(recipes[:,2])
ingredients_min = np.min(recipes[:,1])
ingredients_max = np.max(recipes[:,1])
ingredients_median = np.median(recipes[:,1])
print('Среднее значение для ингредиентов = ', ingredients_average_value)
print('Минимальное значение для ингредиентов = ', ingredients_min)
print('Максимальное значение для ингредиентов = ', ingredients_max)
print('Медиана для ингредиентов = ', ingredients_median)

Среднее значение для ингредиентов =  9.05528
Минимальное значение для ингредиентов =  0
Максимальное значение для ингредиентов =  2147483647
Медиана для ингредиентов =  40.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [4]:
print(recipes[:,1:2].max())
minutes = recipes[:,1:2]
block = np.clip(minutes, 0, np.quantile(minutes, 0.75))
print(block)
print(block.max())

2147483647
[[60.]
 [25.]
 [10.]
 ...
 [65.]
 [ 5.]
 [65.]]
65.0


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [9]:
print(len(recipes[:,1:2][recipes[:,1:2] == 0]))
recipes[:,1:2][recipes[:,1:2] == 0] = 1

0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [10]:
uniq_recipes = np.unique(recipes, axis=0)
len(uniq_recipes)


100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [12]:
uniq_ingredients = np.unique(recipes[:,2])
print(len(uniq_ingredients))

37


## Лабораторная работа №1.2

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [14]:
recipes_with_no_more_5ing = recipes[recipes[:,2] <= 5]
print(recipes_with_no_more_5ing)
print("Длинна нового массива: ", len(recipes_with_no_more_5ing))

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]
Длинна нового массива:  17262


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [16]:
ing_for_min = np.array([])
for e in range(recipes.shape[0]):
    ing_for_min = np.append(ing_for_min, recipes[:,2][e]/recipes[:,1:2][e])
print(ing_for_min)
print(ing_for_min.max())

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [17]:
top100_rec = np.argsort(recipes[:,1:2])[:100:-1] # индексы рецептов с наибольшей продолжительностью 
ingr = np.array([])
for i in top100_rec:
    ingr = np.append(ingr, recipes[:,2][i])
np.average(ingr)

16.0

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [18]:
random_recipes = np.random.randint(0, recipes.shape[0], 10)
print(recipes[random_recipes])

[[489986     30     10]
 [287836     35     10]
 [ 17977     90      7]
 [ 93366     85     10]
 [325217     48     14]
 [455643     95      8]
 [118641   1455      7]
 [ 32403     15      8]
 [ 44391     55     11]
 [108157     25     13]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [19]:
aver_ing = np.average(recipes[:,2])
no_more_aver = recipes[:,2][recipes[:,2] < aver_ing]
len(no_more_aver)/len(recipes)*100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [3]:
import numpy as np
simple_rec2 = np.array((recipes[:, 1] <= 20) & (recipes[:, 2] <= 5)).reshape(-1,1).astype('int')
new_recipes2 = np.concatenate((recipes, simple_rec2), axis=1)
new_recipes2

NameError: name 'recipes' is not defined

13. Выведите процент "простых" рецептов в датасете

In [ ]:
(simple_rec2[simple_rec2 == 1].shape[0] / simple_rec2.shape[0]) * 100

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.